package tool.TRANSPORTauto;

import java.util.Scanner;

public class DipoleFactory {
    public static void main(String[] args) {
        //individual55();
        //individual44();
        //individual33();
        //individual5();
        //middle();//in 7 double n
        //cosyMiddle();

        individual45_3();
        individual45_5();
    }

    private static void individual45_5() {
        double n = 60.0;
        double a1 = 9;
        double a2 = 9;
        double a3 = 45-2*a1-2*a2;
        double a4 = a2;
        double a5 = a1;
        double r = 1.0;
        double innerGap = 0.000;
        double halfAperture = 30.0;
        int num = 5;
        String familyName = "CD";
        System.out.println("--------------------------------------------------------------");
//        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
//        System.out.println(String.format("16. 5. %f;",halfAperture));
        reversePart(a1,r,-n,familyName+1,innerGap);
        reversePart(a2,r,n,familyName+2,innerGap);
        reversePart(a3,r,-n,familyName+3,innerGap);
        reversePart(a4,r,n,familyName+4,innerGap);
        reversePart(a5,r,-n,familyName+5,innerGap);

//        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");

    }

    private static void individual45_3() {
        double n = 26.3;
        double a1 = 5.912;
        double a2 = 45-2*a1;
        double a3 = a1;
        double r = 1.0;
        double innerGap = 0.30;
        double halfAperture = 30.0;
        int num = 3;
        String familyName = "CD";

        System.out.println("--------------------------------------------------------------");
//        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
//        System.out.println(String.format("16. 5. %f;",halfAperture));
        reversePart(a1,r,n,familyName+1,innerGap);
        reversePart(a2,r,-n,familyName+2,innerGap);
        reversePart(a3,r,n,familyName+3,innerGap);

//        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");
    }

    private static void individual44() {
        double n = 7.319043832104128;//归一化四极场梯度
        double a1 = 14.82569634691212;
        double a2 = 17.11592979740899;
        double a3 = 13.12214177542972;
        double a4 = 22.34395679207865;//角度分配
        double r = 0.5;//半径
        double innerGap = 0.00;//内间距
        double gap = 0.20;//段间距
        double halfAperture = 45;//孔径mm
        String familyName = "CD4";//命名前缀
        int num = 4*2;//数量

        System.out.println("--------------------------------------------------------------");
        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
        System.out.println(String.format("16. 5. %f;",halfAperture));
        part(a1,r,n,familyName+0,innerGap);
        part(a2,r,-n,familyName+1,innerGap);
        part(a3,r,n,familyName+2,innerGap);
        part(a4,r,-n,familyName+3,innerGap);

        System.out.println();
        System.out.println(String.format("3. %f;",gap));

        part(a4,r,-n,familyName+5,innerGap);
        part(a3,r,n,familyName+6,innerGap);
        part(a2,r,-n,familyName+7,innerGap);
        part(a1,r,n,familyName+8,innerGap);

        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");
    }

    private static void individual5() {
        double n =  6.184683181236861;//归一化四极场梯度
        double a1 = 15.18396593807360;
        double a2 = 28.23535344065623;
        double a3 = 48.16136124174692;//角度分配
        double r = 0.50;//半径
        double innerGap = 0.00;//内间距
        double gap = 0.00;//段间距
        double halfAperture = 45;//孔径mm
        String familyName = "CD4";//命名前缀
        int num = 5;//数量

        System.out.println("--------------------------------------------------------------");
        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
        System.out.println(String.format("16. 5. %f;",halfAperture));
        part(a1,r,-n,familyName+0,innerGap);
        part(a2,r,n,familyName+1,innerGap);
        part(a3,r,-n,familyName+2,innerGap);
        part(a2,r,n,familyName+3,innerGap);
        part(a1,r,-n,familyName+4,innerGap);


        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");
    }

    private static void cosyMiddle() {
        Scanner scanner = new Scanner(System.in);
        int i = 0;
        while(scanner.hasNext()){
            if(i==0){
                System.out.println();
            }

            String s = scanner.nextLine();
            System.out.println("    QG"+i+" := "+s+" ;");
            i++;
        }
    }

    private static void middle() {
        try {
            Scanner scanner = new Scanner(System.in);
            double[] ns = new double[10];
            for (int i = 0; i < 7; i++) {
                ns[i] = scanner.nextDouble()*10.0;
            }

            System.out.println("--------------------------------------------------------------");
            System.out.println("(Generated By Python; pre)");


            System.out.println(String.format("5. 0.27 %f 30. /QG0/ ;",ns[0]));
            System.out.println("3. 0.35 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG1/ ;",ns[1]));


            System.out.println("(End of Python Generated Script)");
            System.out.println("--------------------------------------------------------------");




            System.out.println("--------------------------------------------------------------");
            System.out.println("(Generated By Python; middle)");

            System.out.println("3. 0.3 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG2/ ;",ns[2]));
            System.out.println("3. 0.4 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG3/ ;",ns[3]));
            System.out.println("3. 0.4 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG4/ ;",ns[4]));
            System.out.println("3. 0.4 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG5/ ;",ns[5]));
            System.out.println("3. 0.48 ;");
            System.out.println(String.format("5. 0.27 %f 30. /QG6/ ;",ns[6]));
            System.out.println("3. 0.8 ;");


            System.out.println("(End of Python Generated Script)");
            System.out.println("--------------------------------------------------------------");


        }catch (Exception e){e.printStackTrace();}
    }

    private static void individual33() {
        double n =7.427300489767591;//归一化四极场梯度
        double a1 = 20.05405529128866;
        double a2 = 27.39188941801415;
        double a3 = 0.0;//角度分配
        double r = 0.5000000000000000;//半径
        double innerGap = 0.00;//内间距
        double gap = 0.20;//段间距
        double halfAperture = 45;//孔径mm
        String familyName = "CD4";//命名前缀
        int num = 3*2;//数量

        System.out.println("--------------------------------------------------------------");
        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
        System.out.println(String.format("16. 5. %f;",halfAperture));
        part(a1,r,-n,familyName+0,innerGap);
        part(a2,r,n,familyName+1,innerGap);
        part(a1,r,-n,familyName+2,0);

        System.out.println();
        System.out.println(String.format("3. %f;",gap));

        part(a1,r,-n,familyName+3,innerGap);
        part(a2,r,n,familyName+4,innerGap);
        part(a1,r,-n,familyName+5,0);

        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");
    }

    private static void individual55() {
        double n = 31.36568864894218;//归一化四极场梯度
        double a1 = 9.696876228314373;
        double a2 = 13.42259744711799;
        double a3 = 21.26105264196881;//角度分配
        double r = 1.2;//半径
        double innerGap = 0.00;//内间距
        double gap = 0.20;//段间距
        double halfAperture = 45;//孔径mm
        String familyName = "CD4";//命名前缀
        int num = 5*2;//数量

        System.out.println("--------------------------------------------------------------");
        System.out.println("(Generated By Python; Second 135deg. Combined Function Dipole)");
        System.out.println(String.format("16. 5. %f;",halfAperture));
        part(a1,r,-n,familyName+0,innerGap);
        part(a2,r,n,familyName+1,innerGap);
        part(a3,r,-n,familyName+2,innerGap);
        part(a2,r,n,familyName+3,innerGap);
        part(a1,r,-n,familyName+4,0);

        System.out.println();
        System.out.println(String.format("3. %f;",gap));

        part(a1,r,-n,familyName+5,innerGap);
        part(a2,r,n,familyName+6,innerGap);
        part(a3,r,-n,familyName+7,innerGap);
        part(a2,r,n,familyName+8,innerGap);
        part(a1,r,-n,familyName+9,0);

        System.out.println("(End of Python Generated Script)");
        System.out.println("--------------------------------------------------------------");

    }

    private static void part(double a,double r,double n,String name,double innerGap) {
        System.out.println();
        System.out.println("20. 180.0 ;");
        System.out.println("2. 0 /A1/ ;");
        System.out.println(String.format("4. %f %f %f /%s/ ;",a/180*Math.PI*r, a, n, name));
        System.out.println("2. 0 /B1/ ;");
        System.out.println("20. -180.0 ;");
        System.out.println();
        if(innerGap!=0){
            System.out.println(String.format("3. %f;",innerGap));
        }
    }

    private static void reversePart(double a,double r,double n,String name,double innerGap) {
        System.out.println();
        System.out.println("20. -180.0 ;");
        System.out.println("2. 0 /A1/ ;");
        System.out.println(String.format("4. %f %f %f /%s/ ;",a/180*Math.PI*r, a, n, name));
        System.out.println("2. 0 /B1/ ;");
        System.out.println("20. 180.0 ;");
        System.out.println();
        if(innerGap!=0){
            System.out.println(String.format("3. %f;",innerGap));
        }
    }
}

//20. 180.0 ;
//2. 0 /A1/ ;
//4. 0.2239 12.827 18.03718334875529 /CD12/ ;
//2. 0 /B1/ ;
//20. -180.0 ;
//
//3. 0.10;
